### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by Dexil123** [bigretromike/nakamori#339] opened 2019-08-02 20:33 UTC
Sometimes I get a pop-up message when playing a video. 
![playback-failed-kodi-error](https://user-images.githubusercontent.com/32413969/62396991-dc65be80-b574-11e9-8c65-1cb805b267d3.png)

The video starts but the message takes the focus. After clicking OK it stops the video. And usually no error message is shown after playing the same again.
[kodi.log](https://github.com/bigretromike/nakamori/files/3462820/kodi.log)

**Comment by bigretromike** [comment] 2019-08-02 21:01
Which version are you using?

**Comment by Dexil123** [comment] 2019-08-02 21:02
3.3

**Comment by bigretromike** [comment] 2019-08-02 21:21
I know that this issue could occur when the timeout is set to low in settings and shoko server don't response quickly enough. 
I will look into it, any more info is welcomed

**Comment by Dexil123** [comment] 2019-08-02 21:45
The timeout setting under "Video settings"? 
I just tried changing query timeout to 600 (was 60) same error occurred. 
Also tried to change Max time to wait for buffer to 10000. But that also didn't work. 

The weird thing is. It does play the video just fine.

After messing with it a bit I think I figured it out. It has to do with Kodi settings.
If under Settings > Media > Videos > Default select action is set to Show information then there is a chance the error will occur. After changing it to Play it didn't give me a Playback error.

**Comment by bigretromike** [comment] 2019-08-02 21:49
That could be it !
I will try to do the opposite and try to fix that because I remember that we had this issue before - but maybe something got lost while it was rewriten

**Comment by bigretromike** [comment] 2019-08-09 20:28
@Dexil123 I did some work...
I did not test this heavily but I did not get that error even once after some work.

The update is on dev-channel, if you could test it those are the components (in case you want to update manually):
- plugin 3.4.0~beta2
- script 3.4.0~beta2
- lib 3.4.0~beta4
- player 3.4.0~beta4

**Comment by Dexil123** [comment] 2019-08-11 09:58
I still get it once I set it "Show information".
Tried it on my laptop and coreelec.

**Comment by bigretromike** [comment] 2019-08-11 10:12
could you enable debug log, try to make it happen and post that debug log here ?
hope you checking with dev versions 3.4.0~beta

**Comment by Dexil123** [comment] 2019-08-11 10:37
[kodi - kopie (2).log](https://github.com/bigretromike/nakamori/files/3489866/kodi.-.kopie.2.log)

**Comment by bigretromike** [comment] 2019-08-11 11:44
Ok, I think I can capture this even often than before... 
I'm looking into this right now.

**Comment by bigretromike** [comment] 2019-08-11 13:40
For reference this is the code that throw this error (PlayListPlayer.cpp)
```
if ((m_iFailedSongs >= advancedSettings->m_playlistRetries && advancedSettings->m_playlistRetries >= 0)
        || ((XbmcThreads::SystemClockMillis() - m_failedSongsStart  >= static_cast<unsigned int>(advancedSettings->m_playlistTimeout) * 1000) &&
            advancedSettings->m_playlistTimeout))
    {
      CLog::Log(LOGDEBUG,"Playlist Player: one or more items failed to play... aborting playback");
```
It would trigger every 5 execution, no matter what file would you use.

Solution would be use of 
```
advancedsettings.xml 
```
```
<advancedsettings>
  <playlisttimeout>200</playlisttimeout> 
  <playlistretries>100</playlistretries>
</advancedsettings>
```

**Comment by bigretromike** [comment] 2019-08-11 13:41
Could you report back @Dexil123 because I cannot reproduce the issue with this setting

**Comment by bigretromike** [comment] 2019-08-11 13:53
I would guess that using 'Show Information' and 'Play' trigger different route which include PlayList to be involved.

**Comment by bigretromike** [comment] 2019-08-11 14:24
Looks like a Kodi bug from 17.6, for reference: https://github.com/xbmc/xbmc/issues/16481

**Comment by anxdpanic** [comment] 2019-08-11 19:44
iirc this can occur when using `xbmc.Player().play() ` when `xbmcplugin.setResolvedUrl()` is expected.

Changing https://github.com/bigretromike/nakamori.player/blob/e00d56634aa1251ca931346bab761a6df152097f/lib/nakamori_player.py#L157-L160
to something like;
```
if is_transcoded:
	url_for_player = m3u8_url
else:
	url_for_player = file_url
item.setPath(url_for_player)

handle = int(sys.argv[1])
if handle == -1:
	player.play(item=url_for_player, listitem=item)
else:
	xbmcplugin.setResolvedUrl(handle, True, item)
```
might resolve the issue. I haven't deep dived the code and am unable to test myself, so I'm sorry if this is just noise.

**Comment by da3dsoul** [comment] 2019-08-11 21:09
We can't use setResolvedUrl, as that forces the built in Kodi player with no callbacks. We need the callbacks for scrobbling and stuff.

**Comment by anxdpanic** [comment] 2019-08-11 21:32
setResolvedUrl just starts playback, callbacks are still usable. I do this in a few add-ons.

**Comment by bigretromike** [comment] 2019-08-12 05:06
@anxdpanic thanks for the tip, I will test it - I stopped using `setResolvedUrl` at beginning of development because most of the time I would end up wi `Unable to play` errors.

Looks like it a good reason to check this out.

@anxdpanic any reason why we should check for handle to be `-1` ? I would understand that the handle will be `-1` aka missing only when scripts are involved, right ? or is it just a safe case ?

**Comment by bigretromike** [comment] 2019-08-12 05:57
> 
> 
> iirc this can occur when using `xbmc.Player().play() ` when `xbmcplugin.setResolvedUrl()` is expected.
> 
> Changing https://github.com/bigretromike/nakamori.player/blob/e00d56634aa1251ca931346bab761a6df152097f/lib/nakamori_player.py#L157-L160
> to something like;
> 
> ```
> if is_transcoded:
> 	url_for_player = m3u8_url
> else:
> 	url_for_player = file_url
> item.setPath(url_for_player)
> 
> handle = int(sys.argv[1])
> if handle == -1:
> 	player.play(item=url_for_player, listitem=item)
> else:
> 	xbmcplugin.setResolvedUrl(handle, True, item)
> ```
> 
> might resolve the issue. I haven't deep dived the code and am unable to test myself, so I'm sorry if this is just noise.

I implemented your suggestion. It also end up with:
```
Found method: Playlist.OnAdd
2019-08-12 07:48:41.973 T:18446744073709551614   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nakamori/episode/77944/file/0/play]
```

Also its looks like that using `setResolvedUrl` also cache somehow results (resolving result?) so if it fail even once then it will be always failing (in this case). And Im getting even less proper plays that by using `.play` for some reason - which is opposite from what I have read about `setResolvedUrl`. Also Im checking this against 19.0 so maybe its a regression or something.

**Comment by bigretromike** [comment] 2019-08-12 07:04
The issue with `setResolvedURL` is that by using `handle = int(sys.argv[1])` and using that handle it gives me `WARNING: Attempt to use invalid handle ` thats why it ends not working (probably), while using `.play` does not have that issue.

**Comment by bigretromike** [comment] 2019-08-12 07:31
```
    global plugin_dir
    plugin_dir.success = False
    del plugin_dir
```
This code would break `setResolvedUrl`
With setResolvedUrl it looks a bit better while playing, I will investigate more and throw out hacks like those ;-) it hard to debug anything

**Comment by bigretromike** [comment] 2019-08-12 09:12
@anxdpanic while heavily tested, looks like your workaround did helped, also it resolved few others issues and I like the way it works. thank you very much!

**Comment by bigretromike** [comment] 2019-08-12 09:29
@Dexil123 test with minimum 3.4.0~beta10; if the issue persist please re-open;

**Closed by bigretromike** 2019-08-12 09:29 UTC
Labels: Bug, Waiting for Confirmation

**Comment by anxdpanic** [comment] 2019-08-12 14:47
Happy to hear it helped. 👍 

>@anxdpanic any reason why we should check for handle to be -1 ? I would understand that the handle will be -1 aka missing only when scripts are involved, right ? or is it just a safe case ?

The `handle == -1` check is partly a safe case, and should ensure that `Player().play()` is only used when executed via script/non-playable list items.

I don't believe this is a bug in core, and is more about the context in which `Player().play()` is called.  `Player().play()` being intended for scripts, and `setResolvedUrl` intended for add-ons.

**Comment by bigretromike** [comment] 2019-08-12 16:29
@anxdpanic with current structure its hard to tell where addon ends and where scripts start. Im still thinking that there is a bug in core. 
With almost 100% success I would trigger this bug with every 5th run of same file, and the internal values would looked funky, and using `advancesetting` file would post-pone the issue a lot. 

Imo, I was never fun of many hacks that were needed to make something work as intended, but then again I don't want to drop Kodi just because it has ancient bugs that no one cared to make issue about, so no one ever did give them a time to resolve :)

I'm happy that this `small` and not critical issue someone how lure you in (could that the the issue on xbmc?) and the direction you gave did resolve few bigger issues 👍

**Comment by anxdpanic** [comment] 2019-08-12 16:57
It was the issue on xbmc/xbmc, I've seen similar issues in a couple add-ons so I thought to bring it to your attention.

I'm not sure how it's implemented in core(no C++ knowledge), my best guess would be that `Playback failed` likely happens because `setResolvedUrl` seems to be an equivalent to an `endOfDirectory` signal for playable list items, as well as starting playback. So when using `Player().play()` in that context, that signal never happens and results in the error. No idea what would cause it to be intermittent like that though.

**Comment by bigretromike** [comment] 2019-08-12 17:34
You see yourself, if it would fail everytime with `play` there wouldn't be a problem... but it works most of the time. I tried to debug that in c++ and for the first look it would looks like its a bug in core, but who knows. Also each plugin is different, for example the issue I had with `setResolvedUrl` came from fact that we moved to `plugin.routing` and to make `play` work we would delete root of the `ListControl` because without that we would have `loading` until you hit `esc` :-) 

Time will show, someone will probably close my issue anyway but for future reference im leaving it there, maybe there is a bug there - or maybe the bug is because the way we used it before :-) and someone will `exclude` it from there so other wont use it `play` that way.. 

But once again, thank you very much !
